export const DB = {
  tables: {
    users: 'users',
    admin: 'admin',
    student: 'student',
    classes: 'classes',
    classInstances: 'class_instances',
    attendance: 'attendance',
    academicYears: 'academic_years',
    subjects: 'subjects',
    timetableSlots: 'timetable_slots',
    schoolCalendarEvents: 'school_calendar_events',
    classAdmins: 'class_admins',
    feeComponentTypes: 'fee_component_types',
    feeStudentPlans: 'fee_student_plans',
    feeStudentPlanItems: 'fee_student_plan_items',
    feePayments: 'fee_payments',
    tests: 'tests',
    testQuestions: 'test_questions',
    learningResources: 'learning_resources',
    tasks: 'tasks',
    syllabi: 'syllabi',
    syllabusChapters: 'syllabus_chapters',
    syllabusTopics: 'syllabus_topics',
    syllabusProgress: 'syllabus_progress',
  },
  columns: {
    id: 'id',
    createdAt: 'created_at',
    updatedAt: 'updated_at',
    schoolCode: 'school_code',
    classInstanceId: 'class_instance_id',
    academicYearId: 'academic_year_id',
    subjectId: 'subject_id',
    teacherId: 'teacher_id',
    studentId: 'student_id',
    startDate: 'start_date',
    endDate: 'end_date',
    paymentDate: 'payment_date',
    periodNumber: 'period_number',
    classDate: 'class_date',
    startTime: 'start_time',
    endTime: 'end_time',
    status: 'status',
    title: 'title',
    fullName: 'full_name',
    email: 'email',
    phone: 'phone',
  },
} as const;

export type TableName = typeof DB.tables[keyof typeof DB.tables];

